# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppbgarch11 <- function(x) {
    .Call(`_RobGARCH_rcppbgarch11`, x)
}

rcpp_hello_world <- function() {
    .Call(`_RobGARCH_rcpp_hello_world`)
}

